# Buck 业务前端 K8s 模板，CI 会替换占位符。
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project-name-placeholder
  name: project-name-placeholder-deploy
  namespace: ns-placeholder
spec:
  replicas: replicas-placeholder
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: project-name-placeholder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project-name-placeholder
    spec:
      containers:
        - name: project-name-placeholder-container
          image: registry-dir-placeholder/project-name-placeholder:version-placeholder
          imagePullPolicy: Always
          ports:
            - containerPort: http-port-placeholder
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: harbor-secret

---

apiVersion: v1
kind: Service
metadata:
  name: project-name-placeholder-service
  namespace: ns-placeholder
spec:
  selector:
    app: project-name-placeholder
  ports:
    - protocol: TCP
      name: http-port
      port: http-port-placeholder
      targetPort: http-port-placeholder

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-name-placeholder
  namespace: ns-placeholder
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - host-placeholder
      secretName: tls-cert
  rules:
    - host: host-placeholder
      http:
        paths:
          - pathType: Prefix
            path: prefix-placeholder
            backend:
              service:
                name: project-name-placeholder-service
                port:
                  number: http-port-placeholder
