pluginManagement {
    repositories {
        maven { url = uri(System.getenv('NEXUS_MAVEN_URL') ?: '') }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri(System.getenv('NEXUS_MAVEN_URL') ?: '') }
        mavenCentral()
    }
}

rootProject.name = 'brick-upper-backend'
